# .streamlit/secrets.toml
TOGETHER_API_KEY = "your-actual-api-key"
newsapi = "your_newsapi_key"

[reddit]
client_id = "your_reddit_client_id"
client_secret = "your_reddit_client_secret"
user_agent = "your_app_user_agent"
